#!/bin/bash

# busguardian related hacks/shortcuts which increase productivity

usage ()
{
    echo "Options available:"
    echo "  busgd nw <INTERFACE>"
    echo "  busgd serial"
    echo "  busgd flash"
}

# TODO (vaseeja) hardcoded IP address and device name
setup_network ()
{
   sudo ifconfig br-avprivate down
   local INTERFACE=$1
   echo "bringing $INTERFACE down"
   sudo ifconfig $INTERFACE down
   echo "assigning IP address to $INTERFACE"
   sudo ip ad add 10.161.0.2/24 broadcast 10.161.0.255 dev $INTERFACE
   echo "bringing up $INTERFACE"
   sudo ifconfig $INTERFACE up
   echo "check IP address"
   ifconfig $INTERFACE
}

launch_minicom ()
{
   sudo killall minicom
   sudo minicom -b 115200 -D /dev/ttyUSB0 -C /tmp/mini_$(date +'%Y_%m_%d') -o
}

flash_busgd ()
{
  cd $TOP
  sudo  /home/lyft/.cache/bazel/_bazel_lyft/6de58db54f5ebc38127e731d0c917ae1/external/ti_uniflash/uniflash_4.3.0/deskdb/content/TICloudAgent/linux/ccs_base/DebugServer/bin/DSLite flash --config=bazel/platforms/tms570ls3137/TMS570LS3137_XDS100v2.ccxml --verbose $TOP/bazel-bin/mbedded/applications/motion_control_ecu/$1_control/bin_tms570.hex
  # bazel run //embedded/applications/bus_guardian/propulsion_control:propulsion_control_deploy_jlink
  # local DSLINK=$(find /home/lyft/.cache/bazel/_bazel_lyft/ -name DSLite)
  # local CFG_FILE=bazel/platforms/tms570ls3137/TMS570LS3137_JLink.ccxml
  # local HEX_FILE=bazel-bin/embedded/applications/bus_guardian/$1_control/$1_control.hex
  # local CMD="sudo $DSLINK flash --config $CFG_FILE --verbose $HEX_FILE"
  # echo $CMD
  # `$CMD`
}

build_bg ()
{
  cd $TOP
  ./avctl build //embedded/applications/bus_guardian/$1_control
}

BUSGD_NW=0
BUSGD_SERIAL=0
BUSGD_FLASH=0
BUSGD_BUILD=0
BUSGD_INTERFACE=""

export TOP=/home/lyft/src/avsoftware

for i in $@
do
case $i in
   nw)
   BUSGD_INTERFACE=$2
   BUSGD_NW=1
   shift
   shift
   ;;
   serial)
   BUSGD_SERIAL=1
   shift
   shift
   ;;
   flash)
   BUSGD_FLASH=1
   BUSGD_TARGET=$2
   shift
   shift
   shift
   ;;
esac
done

if [[ $BUSGD_NW = 1 ]]; then
    setup_network $BUSGD_INTERFACE
elif [[ $BUSGD_SERIAL = 1 ]]; then
    launch_minicom
elif [[ $BUSGD_FLASH = 1 ]]; then
    flash_busgd $BUSGD_TARGET
else
    usage
fi
